open_lm/main.py, open_lm/params.py
Add option for _HYBRID_SHARD_ZERO2, which seems to improve performance in some settings.
=> Hybrid sharding change

README.md, eval/eval_openlm_ckpt.py, scripts/generate.py
- made some minor readme bookkeeping changes
- fixed some minor bug in in-memory-evals 
- changed generate.py to mimic the setup from eval, and added instructions here to the readme
=> Fixed up generate.py, added to readme

datapreprocess/ray/ray_cluster_configs/cluster_west.yaml, datapreprocess/ray/readme.md, datapreprocess/ray/tokenize_shuffle.py
still not as fast as I'd like, somehow combining: tokenize + cut to context operation (10 minutes) and shuffle operation (10 minutes) makes things much slower. But the current script works. Will look into speeding this up in follow up PR.
=> Multinode Working Tokenize shuffle

.gitignore, open_lm/train.py, tests/shared.py, tests/test_grad_accum.py
=> Support no_sync when using grad accumulation

open_lm/main.py
Assert that either both or none of `--no-skip-tokens` and `--accurate-total-tokens` is set.
=> Add assertion for flags.

open_lm/main.py
maybe I missed if this is logged somewhere else, sorry in that case.
Harmless (I think) to log and comes in useful when playing with configs
=> main.py: log number of model parameters

.github/workflows/ci.yml, Makefile, open_lm/main.py, open_lm/params.py, requirements_test.txt, tests/test_grad_accum.py
=> tests: run in GitHub Actions

open_lm/main.py, open_lm/model.py, open_lm/precision.py, pyproject.toml, requirements_test.txt, tests/test_grad_accum.py
Allows `test_grad_accum` to pass when run on CPU, thereby allowing it to run in Github actions.
=> Limited cpu support

open_lm/data.py, open_lm/main.py, open_lm/model_configs/open_lm_test_tiny.json, open_lm/params.py, tests/test_training_simple.py
This allows us to do simple tests that call through main(), similar to open_clip: https://github.com/mlfoundations/open_clip/blob/main/tests/test_training_simple.py
=> Add synthetic dataset, test for simple training with synthetic data

open_lm/main.py, open_lm/params.py, open_lm/utils/transformers/hf_wrapper.py
support w/ fsdp
tested with mistral 7b:
--hf-model "mistralai/Mistral-7B-v0.1" \
--hf-seq-len 2048 \
--hf-fsdp-block "MistralDecoderLayer" \
--fsdp \
--fsdp-amp
=> support for training AutoModelForCausalLM directly 

open_lm/file_utils.py, setup.py
An error in log_num_checkpoints was breaking the dataset_manifest + multiple sources code path. This PR fixes that.
=> Fix log_num_checkpoints with multiple sources.

open_lm/main.py
https://github.com/mlfoundations/open_lm/issues/107
=> add parameter compatability check

Makefile, tests/shared.py, tests/test_dataset_deterministic.py, tests/test_dataset_no_resample.py, tests/test_file_utils.py, tests/test_generate_kv_cache_time.py, tests/test_generate_load_kv_cache_equal.py, tests/test_grad_accum.py, tests/test_make_wds_manifest.py, tests/test_save_load.py, tests/test_tiny_generate_kv_cache_equal.py, tests/test_tokenize_shuffle.py
=> Reduce argparse duplication in tests

open_lm/data.py, open_lm/file_utils.py, setup.py, tests/shared.py, tests/test_save_load.py
This fixes some issues caused by #150 - one that broke `log_num_checkpoints.py`, as well as some related to test cases.
=> Fix some extra cases in global batch size.

open_lm/data.py
ran into issues during decompression for json.gz
add handler for to_tuple to log and continue
=> map_handler for to_tuple (decompression issues)

sagemaker_train/launch_sagemaker_train.py
Quick fix to allow debugging locally with `launch_sagemaker_train.py` with `--local` flag.
=> support for local build with sagemaker

open_lm/datapreprocess/ray/ray_cluster_configs/cluster_west.yaml, open_lm/datapreprocess/ray/readme.md, open_lm/datapreprocess/ray/tokenize_shuffle.py
Minor updates:
1. Added two necessary dependencies in ray config.
2. Added `import glob` in `tokenize_shuffle.py`.
3. Fixed typos in README.
=> Added dependencies and updated the readme for tokenize shuffle

open_lm/datapreprocess/ray/tokenize_shuffle.py
Also reduces progress bar logging
=> Make globbing configurable, glob in one pass on s3

open_lm/main.py
I think this check should actually not be done in the loading function since it has to do with training not loading....
Here for example, I want to use this loading function for eval and I don't care about the seed for shard shuffling. To make this quicker I added a flag but a refactor is needed later.
=> allow loading with a different seed with an input flag

open_lm/main.py, setup.py
Make sure that all processes exit at the same time (so that remote is synced properly).
=> Patch dist barrier

open_lm/model.py, open_lm/params.py
Similar to Gemma but with an expansion ratio that matches our Swiglu
=> Add support for GeGLU

open_lm/attention.py, open_lm/model.py, open_lm/utils/llm_foundry_wrapper.py, open_lm/utils/transformers/hf_config.py, open_lm/utils/transformers/hf_model.py, tests/test_attention_masking.py
Results in 18.7 TriviaQA accuracy for a 1B model, compared to ~0% earlier due to the lack of attention_mask support.
=> Generation fixes

open_lm/model_configs/open_lm_11m_v2.json, open_lm/model_configs/open_lm_154m_v2.json, open_lm/model_configs/open_lm_411m_v2.json, open_lm/model_configs/open_lm_79m_v2.json
small-scale configs from language models scale reliably with over-training and on downstream tasks (https://arxiv.org/abs/2403.08540)
=> v2 small-scale configs

open_lm/model.py, open_lm/params.py, open_lm/positional_embedding/rotary.py, setup.py, tests/test_custom_attention.py
This PR adds functionality and optimizations for torch attention and torchcompile.
=> Optimize torchcompile.

open_lm/main.py, setup.py
This PR fixes the state dict when loading a model that has been trained with torchcompile.
=> Fix torchcompile loading.

sagemaker_train/launch_sagemaker_train.py
=> sagemaker use reserved instances

open_lm/logger.py
=> Don't set log level for downstream modules

open_lm/params.py
This adds an error for a corner case of params that is not technically supported.
=> Add error message.

open_lm/train.py
This PR adds more detailed timing for our training run, so that performance can be monitored more closely.
=> Add more detailed timing.
