mlfoundations/open_lm

open_lm/main.py, open_lm/train.py
In cases where loss goes to nan (e.g., bad nodes or bad hparams), we would like to raise an exception, free resources and prevent other issues like saving checkpoints and optimization states that may lead to skipped training on restarts.
=> Exit on NaN loss

open_lm/utils/transformers/config.py, open_lm/utils/transformers/model.py, scripts/generate.py, scripts/generate_without_hf.py
This PR adds two generation scripts. One works with a HuggingFace wrapper (giving access to all of HF `generate`) functionality, and the other is a manual decoding script (initially from @gabrielilharco, then modified by @mitchellnw and @jmercat). I'm PR'ing both as they are useful for complementary purposes, and can help debug each other. Right now, the two scripts return the same outputs when `--temperature` is set to 0, and similar outputs (qualitatively) when temperature is not 0.
In addition, this PR fixes an important bug in our HF wrapper: We were enabling embedding weight tying by default even when our input and output embeddings were trained to be different. This PR fixes that in the first commit.
=> Add generation scripts

README.md, datapreprocess/wiki_download.py, requirements.txt
Added a script in dataprocess to download wikipedia from huggingface for use in the quickstart example (since pile went down recently)
Also modded some things in the requirements.txt to make this script work
=> Replaced pile -> wikipedia in quickstart instructions

open_lm/model.py, requirements.txt
Hi folks,
Congrats on this amazing project!
At HF we do have a Mixin class which is a bit hidden in the docs but it's actually super useful to share models easily on the hub. All you need to do is make sure your class inherits from the [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/v0.17.3/en/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class besides nn.Module, and boom, you automatically get `from_pretrained` and `push_to_hub` for free.
You can now do this:
```
from copy import deepcopy
from open_lm.model import Transformer, Params, _MODEL_CONFIGS
from torch import nn
def get_config(model):
cfg = deepcopy(_MODEL_CONFIGS[model])
config = Params(
dim=cfg["hidden_dim"],
n_layers=cfg["n_layers"],
n_heads=cfg["n_heads"],
seq_len=cfg["seq_len"], …
```
=> Add HF mixin

open_lm/main.py
PyTorch changed the order of the arguments for optim_state_dict_to_load, resulting in confusing error messages when loading checkpoints. This commit fixes that issue. See
Pytorch issue: https://github.com/pytorch/pytorch/issues/105727
Commit that introduced the issue: https://github.com/pytorch/pytorch/commit/580b4702bc862dbce386312900db985df58428c0#diff-ffc1ad1876fbf03d814108f6f2f5950a99281b47e0fd77597745f10dc99add86R1822-R1827
Sample fix: https://github.com/huggingface/accelerate/pull/1755
=> Fix optim_state_dict_to_load call for latest pytorch versions

open_lm/train.py
This should be a free speedup since `evaluate` doesn't have any interaction with autograd.
=> Use inference_mode in evaluate

open_lm/model_configs/open_lm_41m.json
Added a 41m model config; we get relatively reliable scaling starting from the 41m model, and the model lies between the 25m and the 87m model, specifically, the model has 41.01m parameters and 11.94m non-embedding parameters, while those numbers are 24.68m and 5.31m for the 25m model and 87.47m and 38.23m for the 87m model.
=> added 41m model config

open_lm/file_utils.py, open_lm/utils/make_wds_manifest.py
Fix some naming inconsistencies between manifests and the dataloader. This should work with arbitrary shard names.
=> Fix naming inconsistencies.

open_lm/main.py, open_lm/train.py
This fixes #65 - step counting during training was implicitly assuming that all epochs had the same number of steps, which might not hold when using `--no-skip-tokens` and `--accurate-total-tokens`.
=> Fix sample/step counting in the case of uneven epochs.

tests/shared.py
Fixes grad_accum tests so they pass again:
```
tests/test_grad_accum.py::test_grad_acc PASSED                                                                                                                                                                                                                
tests/test_grad_accum.py::test_grad_acc_fsdp PASSED
tests/test_target_masking.py::test_create_replace_before_tok PASSED
```
(The data tests require an assets folder and fail right now unrelated to this PR)
=> Add params to MockArgs

open_lm/data.py
reason for this is - if you're trying out data tokenized with a higher vocab size than you expect this will silently fail and make the data wrong
=> data.py: only x%vocab_size when x < 0

open_lm/data.py, open_lm/params.py, tests/shared.py
Some webdataset files have json issues that throw an error and break training, this logs and skips them instead.
=> Log and skip errors in map_dict

open_lm/data.py, tests/shared.py
This PR makes the shared epoch be common across datasets.
This solves #93 - when updating the dataloader every epoch, only one dataset would get updated, which would make sampling use the same samples for every other dataset (sampling without replacement is not affected by this, since `get_wds_dataset` is called again every epoch).
Results from pytest: 
[tests_fix_shared_epoch.txt](https://github.com/mlfoundations/open_lm/files/13396803/tests_fix_shared_epoch.txt)
=> Shared epoch common for datasets.

open_lm/train.py
if you're just evaluating a pre-trained model with some val-data this bugs out
=> evaluate: set tokens only when args.train_num_samples is not None

open_lm/data.py, setup.py
Decoding was done outside of webdataset, which was not allowing for json.gz items to be loaded.
This PR moves decoding for json files inside the webdataset, and allows for `args.data_key == "json.gz"`.
=> Support json.gz.

open_lm/train.py
faulty line: `start_idx = torch.randint(0, chunk.shape[1] - args.seq_len + 1, (1,)).item()`
if start_idx = chunk.shape[1] - args.seq_len + 1, then:
`targets = chunk[:, start_idx + 1 : start_idx + args.seq_len + 1]` becomes:
```
targets = chunk[:, chunk.shape[1] - args.seq_len + 2 :chunk.shape[1] - args.seq_len + 1 + args.seq_len + 1]
= chunk[:, chunk.shape[1] - args.seq_len + 2 :chunk.shape[1] + 2]
= chunk[:, chunk.shape[1] - args.seq_len + 2 :chunk.shape[1]]
```
thus targets sequence shape is < input sequence shape and the loss raises an error.
=> fixed start index in sample_chunk

open_lm/main.py, open_lm/model.py, open_lm/positional_embedding/rotary.py, tests/shared.py
Allows loading much larger models without using CPU ram, only initializing after we FSDP and shard onto GPU. 
Earlier, we were limited in model size by the memory of a single GPU, due to this line:
https://github.com/mlfoundations/open_lm/blob/005fdccca337f5a84c99bbfecee768a77e90bd9e/open_lm/main.py#L396
Removing that line limits us by the CPU memory of a single node, even in multi-node settings, but this is still not enough for large models (e.g., 34B takes >1TB RAM, crashes a p4).
Now, we are limited by the total GPU memory across nodes, so we can load large models in multi-node setting.
Our model size is now limited by total GPU memory across nodes.
Note: This first requires merging #125
=> Support for initializing models on meta device

open_lm/main.py
https://github.com/mlfoundations/open_lm/pull/127
Above PR changed order from model -> load -> distributed to model -> distributed -> load
load_model automatically removes "module" from keys so above change can break load_model
also breaks if distributed and loading weights that do not include module in keys
this pr check if distributed to decide whether to load state_dict to model or model.module
=> fix load_model module key edit

open_lm/params.py, tests/test_param_parsing.py
This allows us to load parameters from a json or yaml file. If a config is passed via file, then no other arguments are allowed, to avoid confusion due to commandline overrides. Added a few tests that check for equality between config and command line args.
=> Allow parsing parameters from a config file

open_lm/file_utils.py, open_lm/main.py
This is useful for some settings where relative imports don't work (e.g., sagemaker)
=> Turn relative imports into module imports

open_lm/train.py, setup.py
This is just the bugfix part of Samir's PR here https://github.com/mlfoundations/open_lm/pull/149, without the global batch size part.
=> Val list -> tensor bugfix

open_lm/main.py, tests/shared.py, tests/test_save_load.py
Should help address #145, please tell me if I should actually call main as suggested in the issue or if this is fine.
=> Test train save load, with and without fsdp

open_lm/data.py, open_lm/main.py, open_lm/params.py, open_lm/train.py, setup.py, tests/shared.py, tests/test_dataset_deterministic.py, tests/test_dataset_no_resample.py, tests/test_param_parsing.py, tests/test_training_simple.py, tests/test_training_tokens.py
This PR deprecates the per gpu batch size from the command line and replaces it with global batch size.
Tests are also updated to account for this.
=> Replace batch_size with global_batch_size.

tests/test_training_tokens.py
This PR fixes one of the GPU tests, that broke due to a merge commit which handled `create_train_fixtures` somewhat differently.
=> Fix training tokens test.

open_lm/main.py, open_lm/params.py, open_lm/positional_embedding/rotary.py
The meta device initialization seems to have some issues - for example, FSDP does not seem to call reset_parameters on all our modules. Given this, and the fact that we currently aren't targeting models above 34B, let's disable the meta device entirely for now.
=> Disable meta device by default

open_lm/main.py, setup.py
This partially reverts #138. If we use FSDP, we should call load_model directly, instead of model.module.load_model. I tested training and resuming a model using main.py and it works with this commit.
Note that the tests in https://github.com/mlfoundations/open_lm/pull/148 pass despite this bug because of another bug that @kernelmachine discovered incidentally: Our tests are not properly using distributed functionality, because https://github.com/mlfoundations/open_lm/blob/6570b81d60a34ebe902d2b5a0fca04be98108f8c/open_lm/distributed.py#L20-L25 only checks if world_size > 1 (instead of >= 1). This will be tracked in a follow up issue.
=> Fix checkpoint loading and resume for fsdp

open_lm/datapreprocess/ray/tokenize_shuffle.py, tests/test_tokenize_shuffle.py
Add manifest creation in the tokenization script with the new format. The manifests made by this will be compatible with the new dataloader version.
=> Reincorporate manifest creation.

open_lm/distributed.py, open_lm/main.py, open_lm/params.py, tests/shared.py, tests/test_grad_accum.py, tests/test_save_load.py, tests/test_save_load_from_main.py, tests/utils.py
This addresses a few issues with our checkpoint save/load tests, and with checkpoint loading itself:
1. Adds a new test that calls main() to test checkpoint saving and loading, ensuring that our full main() pipeline works correctly.
2. Adds a `--force-distributed` flag that allows us to test distributed code paths on a single gpu. Previously, all our tests were running with args.distributed=False, even when args.fsdp=True.
3. Reverts a bug introduced by #153, which meant we did not automatically resume the latest checkpoint when using s3.
4. Fixes a bug in `--resume latest` which led to checkpoints being ignored when resuming in the case of local checkpoints without remote-sync.
Closes #170
=> Fix checkpoint loading and checkpoint tests

open_lm/attention.py, open_lm/model.py, open_lm/params.py
I encountered the following issue: 
ExecutorError: HuggingFace error: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead. Request: 
Request(model_deployment='open_lm/default-open_lm_1b', model='open_lm/default-open_lm_1b', embedding=False, prompt='Passage: The Little White Bird is a series of short episodes, including both accounts of the narrator\'s day-to-day activities ... inheritance.\nQuestion: What is bigamy?\nAnswer:', temperature=0.0, num_completions=1, top_k_per_token=1, max_tokens=100, stop_sequences=['\n'], 
echo_prompt=False, top_p=1, presence_penalty=0, frequency_penalty=0, random=None, messages=None, multimodal_prompt=None)
and I was able to fix it by adding `.contiguous()` …
=> fix: add contiguous to xformers_attn

open_lm/file_utils.py, open_lm/main.py, open_lm/params.py, tests/test_file_utils.py
This PR adds an extra flag `--multiple-data-passes` which allows for multiple passes over the dataset.
The code is set up so that the total number of tokens that will be seen across all passes of the dataset will still be `epochs * train_num_samples`, only in this case instead of erroring when data runs out, we move on to the next pass of the dataset (shuffling the shards as well, so that we see them in different order in each pass).
This is a WIP, since a few more test cases need to be added.
=> Enable multiple passes over the dataset.

open_lm/utils/llm_foundry_wrapper.py
human_eval tasks have a corresponding metric type, InContextLearningCodeEvalAccuracy, which was not included in the llm foundry wrapper. As a result, human_eval metrics were not being written to the evaluation output file.
=> added InContextLearningCodeEvalAccuracy to evaluation metrics

open_lm/distributed.py, open_lm/params.py
This option adds the ability to preset the world size to be used, when working on a SLURM cluster, overriding the world size provided by the environment variables.
This is helpful in cases where a different number of GPUs per node need to be used, to account for clusters with non-standard number of GPUs per node.
=> Add the ability to preset world size.

open_lm/main.py
DDP + --grad-checkpointing resulted in but works with FSDP
```
AttributeErrorAttributeErrorAttributeError: : 'DistributedDataParallel' object has no attribute 'set_grad_checkpointing
': 'DistributedDataParallel' object has no attribute 'set_grad_checkpointing''DistributedDataParallel' object has no at
tribute 'set_grad_checkpointing'    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")  
AttributeError: 'DistributedDataParallel' object has no attribute 'set_grad_checkpointing' 
```
I guess FSDP passes along set_grad_checkpointing to the module but not DDP. This works with both configurations
=> main.py: set_grad_checkpointing before DDP or FSDP wrap

open_lm/main.py, open_lm/params.py, open_lm/train.py, open_lm/utils/averaging_utils.py
Supports EMA and polynomial averaging. Includes option for more than one averaged model and taking intermittent averaging.
For example, running EMA with parameter 0.999 and period 100 and polynomial averaging with parameter 8 and period 10, use
`--averagers="ema_0.999_100,poly_8_10"`
Logging of training loss of the averaged models can be done by choosing `--log-avg-model-training-loss` to be bigger than zero.
=> Adding averaging of iterates

eval/eval_openlm_ckpt.py, open_lm/model.py, open_lm/utils/llm_foundry_wrapper.py, open_lm/utils/transformers/hf_model.py, requirements.txt, requirements_test.txt, tests/utils.py
This allows calling the model with inputs_embeds arguments instead of input_ids if needed.
It also removes llm-foundry from the requirements. It is already explained in the README that llm-foundry is a separate additional installation to make. 
llm-foundry is extremely strict in its requirements and makes a lot of packages incompatible with OpenLM so I don't think it should be required. Moreover it's only used for eval so it is not actually required by the main model.
=> Input embed

open_lm/datapreprocess/ray/tokenize_shuffle.py
Added a presort flag to tokenize shuffle that we need for in-context-pretraining. 
We can remove this flag at any point, or the ICLM tok/shuffle steps can be done from this branch. Either/or
=> Presorting tokenize shuffle (useful for in-context-learning)

README.md
The current readme references `datapreprocess/wiki_download.py` and `datapreprocess/wiki_download.py` which now both live in the `openlm` directory. This change simply updates the paths in the readme for correctness.
=> Updating paths in readme to reflect current codebase

open_lm/main.py
Allows for using a different seed when starting from a pretrained checkpoint but not loading the pretrained state.
=> use different_seed=True when args.load_pretrained_state is false

open_lm/train.py, setup.py
Due to the ordering of the loss resets, training would not actually exit if a NaN value was encountered. This PR fixes this.
=> Fix order of loss resets.

open_lm/datapreprocess/ray/tokenize_shuffle.py, open_lm/utils/convert_llama.py, tests/test_dataset_no_resample.py, tests/test_file_utils.py, tests/test_training_tokens.py
Current Issue: 
Some sources (e.g. code repos, books) are prone to having very long pages leading to long lists of tokens. However, the way we currently yield sequences is to simply add all tokens from a page to the buffer and to then repeatedly slice the buffer. When buffer grows too large this can be very slow (and many slices need to take place). 
Solution:
Control the max buffer size by yielding tokens from a page's token set to the buffer in a more controlled manner.
=> make tokenize-shuffle more robust to long pages

open_lm/main.py, open_lm/params.py, tests/test_training_simple.py
This PR adds two flags:
- `--data-tolerate-error-p`: The percentage of tokens that should be seen by a checkpoint before we think it's a failure.
- `--data-tolerate-num-ckpts`: The maximum number of such failed checkpoints we allow.
=> Improve error handling for s3 read errors.

open_lm/main.py
When tolerance for ratio of tokens seen within epoch fails, no local directory for args.failed_checkpoint_path
=> args.failed_checkpoint_path makedir
